export default {
  HEADER: "header",
  ADD_NEW_ITEMS: "ADD_NEW_ITEMS",
  ADD_NEW_SEARCH_ITEM: "CONSTANTS.ADD_NEW_SEARCH_ITEM",
  HANDLE_ERROR: "HANDLE_ERROR",
  HANDLE_DELETE: "HANDLE_DELETE",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  DELETE_FROM_FAVORITES: "DELETE_FROM_FAVORITES",
  TOGGLE_LOADING: "LOADING",
  EMPTY_RESPONSE: "There were no properties found for the given location",
};
